// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace Repository.Migrations.MsgUsers
{
    [DbContext(typeof(MsgUsersContext))]
    [Migration("20220620203119_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("Models.MsgUsers", b =>
                {
                    b.Property<string>("FromId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MessageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToId")
                        .HasColumnType("TEXT");

                    b.HasIndex("FromId");

                    b.HasIndex("MessageId");

                    b.HasIndex("ToId");

                    b.ToTable("MsgUsers", (string)null);
                });


            modelBuilder.Entity("Models.MsgUsers", b =>
                {
                    b.HasOne("Models.User", "From")
                        .WithMany()
                        .HasForeignKey("FromId");

                    b.HasOne("Models.Message", "Message")
                        .WithMany()
                        .HasForeignKey("MessageId");

                    b.HasOne("Models.User", "To")
                        .WithMany()
                        .HasForeignKey("ToId");

                    b.Navigation("From");

                    b.Navigation("Message");

                    b.Navigation("To");
                });
#pragma warning restore 612, 618
        }
    }
}
